### ISSUE TITLE
TruffleRuby support

### ISSUE THREAD

**Issue by deepj** [socketry/socketry#29]
Probably it means to remove hitimes dependency due to https://github.com/oracle/truffleruby/issues/1436

**Comment by ioquatix** [comment]
I believe you can replace `hitimes` with `timers` gem. It no longer depends on `hitimes`. Please feel free to submit a PR.

**Comment by shayneoneill** [comment]
Was this ever fixed?

**Comment by ioquatix** [comment]
No I don't believe so. This particular gem is not under active development either.

**Comment by havenwood** [comment]
@shayneoneill The hitimes maintainer worked with TruffleRuby maintainers to prepare a patch that removes the C and Java dependencies now that a pure Ruby implementation is possible. It hasn't been merged: https://github.com/copiousfreetime/hitimes/pull/73

**Comment by shayneoneill** [comment]
I managed to fork myself a copy of this and just remove the hitimes and it worked. 

And yeah with the unmaintained dependency. Seems to be the way of things. Poor old rubys undergoing pretty savage bit-rot right now in its ecosystem. The "everything must be javascript" cargo cult has been brutal on rails and unfortunately ruby was a bit too dependent on rails being its killer app

**Comment by ioquatix** [comment]
Feel free to submit a PR. That would be great.

**Comment by copiousfreetime** [comment]
Just an FYI - hitimes is quite stable and maintained - no need for any new features just bug fixes and compatibility issues as the ecosystem evolves.

I was waiting on feedback from truffleruby the pull request I sent them (https://github.com/oracle/truffleruby/pull/1594) to allow hitimes to run on truffleruby without a c extension. Apparently that was done in march and I missed the notification. @eregon pinged today to remind me that hitimes was good to go on truffle ruby.

hitimes 2.0.0 is pushed and released, use if you wish.
